apiVersion: v1
kind: Service
metadata:
  name: thunderdome
  labels:
    app: thunderdome
  namespace: thunderdome-k3d
spec:
  selector:
    app: thunderdome
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
